"use client";

import { useEffect } from "react";

const experience = [
  {date:"2025 — Present",role:"Senior Security Operations Engineer",company:"Qualys Security Tech Services",mark:"Q",focus:"Detection · Response · Hunting",impact:"Improving detection quality and incident-response consistency across enterprise environments."},
  {date:"2024 — 2025",role:"Digital Forensic Examiner",company:"Center for Cybercrime Studies",mark:"CCS",focus:"IoT · Forensics · Research",impact:"Examining IoT evidence and supporting applied cybercrime research."},
  {date:"2022 — 2025",role:"IT Engineer",company:"CUNY — John Jay College",mark:"JJ",focus:"Splunk · Labs · Mentoring",impact:"Building security labs, supporting Splunk environments, and mentoring students."},
  {date:"2021 — 2022",role:"Security Operations Engineer",company:"Qualys Security Tech Services",mark:"Q",focus:"SOC · Malware · Automation",impact:"Investigating threats and automating recurring security-operations workflows."},
];

const process = [
 {name:"Signal",text:"Suspicious identity activity creates the first indication."},
 {name:"Context",text:"Review the user, endpoint, authentication history, and surrounding telemetry."},
 {name:"Decision",text:"Determine whether the evidence supports likely account compromise."},
 {name:"Containment",text:"Disable access, preserve evidence, and coordinate the next response action."},
 {name:"Improvement",text:"Tune the detection and update the playbook with what the investigation revealed."},
];

const skills = ["Incident response","Threat hunting","Detection engineering","Digital forensics","Cloud security","Endpoint security","Vulnerability management","SIEM","Python automation","Email security","Identity security","Mentoring"];

export default function Home(){
 useEffect(()=>{
  const observer=new IntersectionObserver(items=>items.forEach(item=>{if(item.isIntersecting)item.target.classList.add("shown")}),{threshold:.1});
  document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
  return()=>observer.disconnect();
 },[]);

 return <main>
  <nav><a className="logo" href="#home">SCD</a><div><a href="#work">Impact</a><a href="#about">About</a><a href="#evidence">Approach</a><a href="#research">Research</a></div><a className="navCta" href="mailto:srinivasa.dumpa@proton.me">Let&apos;s talk</a></nav>

  <header id="home">
   <div className="heroText reveal"><p className="introTag"><i/> SECURITY ENGINEER</p><h1>Srinivasa<br/><span>Dumpa.</span></h1><p className="intro">I investigate complex security incidents, improve how threats are detected, and build repeatable response processes for teams operating at scale.</p><div className="heroActions"><a href="#work">View selected work <b>↘</b></a><a href="./Srinivasa-Dumpa-Resume.pdf" download>Download résumé ↓</a></div></div>
   <aside className="heroCard snapshot reveal"><div className="cardHead"><span>OPERATIONAL SNAPSHOT</span><span>4+ YEARS</span></div><div className="snapshotGrid"><div><b>300+</b><span>Alerts investigated weekly</span></div><div><b>75+</b><span>Detections reviewed</span></div><div><b>40+</b><span>Response playbooks</span></div><div><b>10–15</b><span>Minute MTTA</span></div></div><div className="cardFoot"><p>Evidence from security operations at scale.</p><span>INVESTIGATE<br/>IMPROVE<br/>REPEAT</span></div></aside>
  </header>

  <section className="work" id="work"><div className="heading reveal"><p>OPERATIONAL IMPACT</p><h2>Where judgment became<br/>measurable improvement.</h2></div><div className="projects">
   <article className="project projectOne reveal"><div className="projectCopy"><span>DETECTION ENGINEERING · CASE STUDY</span><h3>Less noise.<br/>Better signal.</h3><p><b>Situation</b> Repeated false positives were obscuring meaningful alerts.</p><p><b>Decision</b> Prioritize tuning by outcome, analyst effort, and risk.</p><p><b>Action</b> Review 75+ use cases and improve logic, correlation, and thresholds with the SIEM team.</p><strong>~25% <i>reduction in false positives</i></strong><a className="evidenceLink" href="#detection-method">View approach ↘</a></div><div className="signalViz" aria-hidden="true"><div className="alertStream">{Array.from({length:18},(_,i)=><i key={i}/>)}</div><div className="filterGate"><span>LOGIC</span><b>+</b><span>CONTEXT</span></div><div className="trustedSignal"><i/><i/><i/><span>HIGHER-CONFIDENCE SIGNAL</span></div></div></article>
   <article className="project projectTwo reveal"><div className="projectCopy"><span>INCIDENT RESPONSE · CASE STUDY</span><h3>Consistency at volume.</h3><p><b>Situation</b> High alert volume required faster, consistent decisions.</p><p><b>Decision</b> Standardize triage, ownership, and escalation points.</p><p><b>Action</b> Improve prioritization and create or update 40+ response playbooks.</p><strong>300+ <i>alerts investigated each week</i></strong><a className="evidenceLink" href="#triage-workflow">View approach ↘</a></div><div className="responseViz" aria-hidden="true"><span>ALERT</span><i/><span>TRIAGE</span><i/><span>CONTAIN</span><b>10–15 min MTTA</b></div></article>
   <article className="project projectThree reveal"><div className="projectCopy"><span>ENDPOINT SECURITY · CASE STUDY</span><h3>Visibility where it was missing.</h3><p><b>Situation</b> Distributed infrastructure lacked dependable endpoint visibility.</p><p><b>Decision</b> Establish consistent telemetry before expanding response coverage.</p><p><b>Action</b> Deploy Qualys FIM, EDR, and EPP across the environment.</p><strong>100+ <i>endpoints · 50+ SCP pods</i></strong></div><div className="endpointViz" aria-hidden="true">{Array.from({length:28},(_,i)=><i key={i}/>)}</div></article>
  </div></section>

  <section className="capabilities"><div className="capHead reveal"><p>CAPABILITIES</p><h2>What I bring to the table.</h2></div><div className="skillCloud reveal">{skills.map(skill=><span key={skill}>{skill}</span>)}</div><div className="toolNote reveal"><p>TOOLS I USE</p><span>Splunk · Elastic · Wazuh · Qualys EDR · Microsoft Defender · Proofpoint · MISP · OpenCTI · VirusTotal · FTK · EnCase · Autopsy · Cellebrite · Wireshark · Nessus</span></div></section>

  <section className="about" id="about"><div className="aboutIntro reveal"><p>ABOUT</p><h2>Security work that<br/>moves beyond the alert.</h2><div><p>I&apos;m working at the intersection of security operations, detection engineering, incident response, and digital forensics. I&apos;m investigating threats, improving how they are detected, and building repeatable processes that are helping teams respond with confidence.</p><p>I&apos;m especially interested in problems where technical investigation, automation, and clear communication are working together.</p></div></div><div className="career"><div className="careerTop"><p className="careerLabel">EXPERIENCE</p><p>Four roles. One steadily expanding security perspective.</p></div>{experience.map((item,i)=><article className="reveal" style={{transitionDelay:`${i*60}ms`}} key={item.role}><div className="careerRail"><span className="companyMark">{item.mark}</span></div><time>{item.date}</time><div className="careerRole"><h3>{item.role}</h3><p>{item.company}</p><em>{item.impact}</em></div><span className="focus">{item.focus}</span><b className="careerArrow">↗</b></article>)}</div></section>

  <section className="evidence" id="evidence"><div className="notesIntro reveal"><p>SECURITY APPROACH</p><h2>The thinking behind<br/>a confident response.</h2><span>One operating sequence, followed by two sanitized examples of how I move from uncertainty toward a defensible next action.</span></div><div className="process reveal"><div className="processLead"><span>IDENTITY INCIDENT</span><p>A suspicious event, followed from signal to improvement.</p></div>{process.map(step=><article key={step.name} tabIndex={0}><h3>{step.name}</h3><p>{step.text}</p></article>)}</div><div className="fieldNotes"><article className="fieldNote reveal" id="detection-method"><header><span>DETECTION TUNING</span><b>NOISE → SIGNAL</b></header><div className="noteBody"><h3>When a detection keeps creating low-value work</h3><p>I start with what analysts are actually seeing, then check whether the logic, available context, and intended risk still line up.</p><div className="noteFlow"><span>Baseline</span><i/><span>Group patterns</span><i/><span>Assess risk</span><i/><span>Tune</span><i/><span>Validate</span></div><blockquote>Useful tuning protects coverage while reducing repeated analyst effort.</blockquote></div></article><article className="fieldNote reveal" id="triage-workflow"><header><span>INCIDENT TRIAGE</span><b>SIGNAL → ACTION</b></header><div className="noteBody"><h3>When the first alert does not tell the whole story</h3><p>I establish scope, bring identity and endpoint context together, and make the next action explicit for everyone involved.</p><div className="noteFlow"><span>Validate</span><i/><span>Enrich</span><i/><span>Prioritize</span><i/><span>Contain</span><i/><span>Learn</span></div><blockquote>Good triage is not more data. It is enough context to make a defensible decision.</blockquote></div></article></div><div className="leadershipNote reveal"><div><span>BEYOND THE INVESTIGATION</span><h3>The work continues after containment.</h3></div><p>I coordinate with SIEM, IT, and infrastructure teams, translate findings into clear next actions, improve shared procedures, and support developing analysts through practical guidance.</p></div></section>

  <section className="research" id="research"><div className="heading reveal"><p>RESEARCH & PUBLICATIONS</p><h2>Work that made it<br/>beyond my desk.</h2></div><div className="papers"><a className="reveal" href="https://www.proquest.com/docview/3083334980?sourcetype=Dissertations%20%26%20Theses" target="_blank" rel="noreferrer"><span>MASTER&apos;S THESIS · 2024</span><h3>Attribute-Based Fine-Grained Access Control Using Verifiable Credentials</h3><p>Designed and evaluated a privacy-focused access-control model with Professor Shweta Jain.</p><b>View thesis ↗</b></a><a className="reveal" href="https://www.questjournals.org/jses/papers/Vol5-issue-2/D05021829.pdf" target="_blank" rel="noreferrer"><span>JOURNAL PUBLICATION · 2020</span><h3>Facial Recognition Attendance System Using Python and OpenCV</h3><p>Co-developed an LBPH-based attendance system and co-authored the published paper.</p><b>Read paper ↗</b></a></div></section>

  <section className="contact"><div className="reveal"><p>WHAT&apos;S NEXT</p><h2>Building a security team that values investigation, engineering, and continuous improvement?</h2></div><div className="contactSide reveal"><p>Let&apos;s connect.</p><a href="mailto:srinivasa.dumpa@proton.me">srinivasa.dumpa@proton.me ↗</a><a href="https://linkedin.com/in/srinivasadumpa" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></section>
  <footer><span>© {new Date().getFullYear()} Srinivasa Dumpa</span><span>Cybersecurity · Incident Response · DFIR</span><a href="#home">Back to top ↑</a></footer>
 </main>
}
